BEGIN TRANSACTION;DROP TABLE IF EXISTS `Extension`;CREATE TABLE IF NOT EXISTS `Extension` (
    `id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    `parsed` TEXT NOT NULL,
    `provided` TEXT NOT NULL
);DROP TABLE IF EXISTS `Error`;CREATE TABLE IF NOT EXISTS `Error` (
    `id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    `format` TEXT NOT NULL,
    `content` TEXT NOT NULL,
    `timestamp` TEXT NOT NULL,
    `field` TEXT NOT NULL,
    `dataset` TEXT NOT NULL,
    `link` TEXT NOT NULL
);DROP TABLE IF EXISTS `Dataset`;CREATE TABLE IF NOT EXISTS `Dataset` (
    `id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    `name` TEXT NOT NULL,
    `field` TEXT NOT NULL,
    `link` TEXT NOT NULL,
    `type` TEXT NOT NULL,
    `content` BLOB,
    `revision_id` TEXT NOT NULL
);DROP TABLE IF EXISTS `Data_pull`;CREATE TABLE IF NOT EXISTS `Data_pull` (
    `id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    `finished` INTEGER NOT NULL,
    `timestamp` TEXT NOT NULL
);COMMIT;